#!/usr/bin/env python

import sys
from easylabeltool.qa_label_txt_parser import parse_qa_label_txt
from easylabeltool.my_logger import logger as _logger


if len(sys.argv) == 1:
    _logger.error(f"Missing argument. \n\n         Usage: parse 'FILEPATH'\n")
elif len(sys.argv) == 2:
    LABEL_FILE = sys.argv[1]
    parse_qa_label_txt(LABEL_FILE, writeToJson=True)
else:
    _logger.error(f"Unexpected arguments: {sys.argv[1:]}")
