#!/usr/bin/env python

import sys
from easylabeltool.qa_class import export_excel_to_json
from easylabeltool.my_logger import logger as _logger

if len(sys.argv) == 1:
    _logger.error(
        """Missing argument.
         Usage:
            qabank 'QA Bank Excel Filepath'  """
    )
elif len(sys.argv) == 2:
    qa_bank_excel = sys.argv[1]
    export_excel_to_json(qa_bank_excel)
else:
    _logger.error(f"Unexpected arguments: {sys.argv[1:]}")
    _logger.error(
        """Usage:
            qabank 'QA Bank Excel Filepath'  """
    )
